### PR TITLE
Add root CHANGELOG.md for guidance

### PR DESCRIPTION
**Pull request by benjie**
## Description

I wanted to know what caused the semver major changes in `@envelop/core` so I looked through the root folder for changelog/release notes; looked at the releases tab on the side (which wasn't particularly helpful) and searched the website, but to no avail. Just as I was about to give up, a thought struck me: "it's a monorepo!", and sure enough, changelogs are available for each package.

This file will hopefully help other people that also didn't think to look in folders.

## Type of change

New repo documentation file.

## Checklist:

- [ ] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

At least I figured this out before DM-ing you! :heart:

### CODE REVIEW

**Comment by EmrysMyrddin** [comment]
By the way, I don't know what happened to the documentation, but the migration guide from v3 to v4 is actually the migration guide from v4 to v5...

**Review by EmrysMyrddin — APPROVED** [review]
Can you run prettier ? Otherwise LGTM :-)

**Comment by EmrysMyrddin** [comment]
Perhaps we could even make a symlink to the core plugin ?

**Comment by benjie** [comment]
Prettier executed!

**Pull request merged**
