### PR TITLE
resource-limitations plugin

### PR DESCRIPTION
**Pull request by n1ru4l**
Related https://github.com/dotansimha/envelop/issues/464

Apply extended validation rules, based on https://docs.github.com/en/graphql/overview/resource-limitations

### CODE REVIEW

**Comment by dotansimha** [comment]
I love it. Just missing a changeset and we can continue:)
Do you think we should allow to customize the suffixes/ input field names?

**Comment by dotansimha** [comment]
~~Also, should it maybe be in a separate package?~~

**Comment by n1ru4l** [comment]
@dotansimha outside the mono repo?

**Comment by dotansimha** [comment]
Oh nevermind, I thought it was part of extended-validation plugin :)

**Comment by dotansimha** [comment]
And maybe we can add another plugin for rate limit based on points / complexity ? (see https://shopify.engineering/rate-limiting-graphql-apis-calculating-query-complexity)

**Comment by n1ru4l** [comment]
@dotansimha Yes lets go 🔥🔥🔥🚀

I also think we should maybe move oneOf to a standalone plugin

**Pull request merged**
