### PR TITLE
docs: `graphql-ws` example

### PR DESCRIPTION
**Pull request by enisdenjo**
Pretty straight forward. Code speaks for itself.

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]
This is awesome!! Thank you @enisdenjo . Happy to see that everything connects together with no issues :)

**Comment by enisdenjo** [comment]
Same here! :D

**Comment by pauloedurezende** [comment]
Hey, @enisdenjo

Do you have any examples or could you help me to integrate the envelop along with graphql-ws? I'm using `fastify` with `fastify-websocket`, [just like this example](https://github.com/enisdenjo/graphql-ws#with-fastify-websocket) you provided...

**Comment by enisdenjo** [comment]
@pauloedurezende simply move the [`useServer` options from the example](https://github.com/dotansimha/envelop/blob/4928da521625b3e42299d2d13ac2cf4597014a1d/examples/graphql-ws/index.ts#L39-L62) to your Fastify `makeHandler`. Make sure to use it [as showcased in the quick start](https://github.com/enisdenjo/graphql-ws#with-fastify-websocket).

**Pull request merged**
