### PR TITLE
Upgrade to Yarn v3

### LINKED ISSUE #874: Upgrade Yarn to v3 ?
**Is your feature request related to a problem? Please describe.**

Yarn v1 is in security maintenance mode only since few years now.

Yarn v2 offers new feature with better support of workspaces and more stable dependency resolver.

Is the migration to yarn v2/3 something you want ? If so, I can give a try to upgrade, I have recently done the migration on multiple repositories.

**Describe the solution you'd like**

You surely know that the main pain point in upgrading to V2 is PnP being the default linker.

The easier way to upgrade is to use the node_modules linker. This removes any imcompatibility (like with TypeScript).

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
## Description

Upgrade to yarn V3 and replaces most simple external tools by yarn new features when possible.

Fixes #874 

## Type of change

Only the tooling of the project changes, nothing should change from user side.

## How Has This Been Tested?

Tried every scripts localy runable and watched the CI logs if anything looks odd.

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

 - [x] Upgrade to yarn V3
 - [x] Ignore logs about incompatible dependencies. They are normal (`esbuild-{arch}`)
 - [x] Fix examples peer dependency issues
 - [x] Use patch procol instead of `patch-package`

### CODE REVIEW

**Comment by EmrysMyrddin** [comment]
There is stil a lot of warning about peer dependencies. This warnings are caused by missing or off range dependency in some packages we depends on.

There is 2 ways of cleaning this warning:
 - Fix the deps upstream. Should be fine for most guild packages but can be dificult for others.
 - Use the `resolutions` field to fix for our repo the depencies

The last solution is to just leave the warning, hoping the maintners will fix there denpendencies in the future.

Which one do you prefere ?

**Comment by dotansimha** [comment]
> There is stil a lot of warning about peer dependencies. This warnings are caused by missing or off range dependency in some packages we depends on.
> 
> There is 2 ways of cleaning this warning:
> 
> * Fix the deps upstream. Should be fine for most guild packages but can be dificult for others.
> * Use the `resolutions` field to fix for our repo the depencies
> 
> The last solution is to just leave the warning, hoping the maintners will fix there denpendencies in the future.
> 
> Which one do you prefere ?

I think we can go with option 2 because it seems simpler and we have more control over it. @n1ru4l thoughts?

**Review by n1ru4l — CHANGES_REQUESTED** [review]
I kind of like the current yarn v1 setup and it just works fine. I don't see a need to upgrade to v3 anymore.

**Comment by saihaj** [comment]
`yarn3` does sound cool and we tried it in https://github.com/dotansimha/graphql-yoga but there were many weird issues it was causing so we had to revert it.

**Comment by dotansimha** [comment]
> `yarn3` does sound cool and we tried it in [dotansimha/graphql-yoga](https://github.com/dotansimha/graphql-yoga) but there were many weird issues it was causing so we had to revert it.

Agree. My current preference is pnpm.

**Comment by EmrysMyrddin** [comment]
For me, the main advantages of yarn v3 is its speed and the workspaces management (which is kind of broken in yarn v1). I use it on every projet now and it's really working well with mono repos.

The tool I find very useful is deduplication and constraints. It allows to easily clean up dependencies across the entire mono-repo.

The only thing is to use the node_modules linker, PnP is not supported by lot of tools and packages.

**Comment by n1ru4l** [comment]
@EmrysMyrddin Can you explain what is broken in yarn1? So far I did not have any "things are broken" experiences.

**Comment by dotansimha** [comment]
> @EmrysMyrddin Can you explain what is broken in yarn1? So far I did not have any "things are broken" experiences.

For me, it's mainly issues caused by nested dependencies and `yarn.lock`. We noticed that `npx yarn-deduplicate` helps in most cases.

**Comment by n1ru4l** [comment]
closing this due to missing feedback from OP.

**Pull request closed without merging**
