### PR TITLE
Save id of persisted operation to the context

### PR DESCRIPTION
**Pull request by kamilkisiela**
No way to actually access context on parse phase so used a workaround.

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]

**Comment by dotansimha** [comment]
> No way to actually access context on parse phase so used a workaround.

Maybe this is something we should change? Thoughts? @kamilkisiela @n1ru4l

**Comment by kamilkisiela** [comment]
`onParse` could schedule a context modification that would be applied on the context building phase. I think this way it's nice and clean.

**Comment by dotansimha** [comment]
@kamilkisiela you can now do it from `onParse` :)

**Comment by kamilkisiela** [comment]
@dotansimha done

**Review by dotansimha — APPROVED** [review]

**Pull request merged**
