### PR TITLE
fix leak of response cache metadata metadata

### LINKED ISSUE #1968: `@envelop/response-cache` is leaking `__responseCacheTypeName` to response payload
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a
     minimal reproduction available on
     [Stackblitz](https://stackblitz.com/edit/node-mncjy3).
  - _Please install the latest `@envelop/*` packages that you are using._
  - _Please make sure the reproduction is as small as possible._
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

In the Stackblitz example I have illustrated that `__responseCacheTypeName` is added to the response - even when this is a cache miss. My test suites jest snapshots is now "dirty" and need to have this entry added to it, which makes me confused if tests are working correctly or not.

Looking at the [code](https://github.com/n1ru4l/envelop/blob/64f243254633692d7401db04081a252aae239135/packages/plugins/response-cache/src/plugin.ts#L339) it seems like this `__responseCacheTypeName` should be deleted but it isn't, not for my case. It rather seems like this plugin is adding this `__responseCacheTypeName`, is this actually the intended behaviour?

**To Reproduce** Steps to reproduce the behavior:

1. Go to stackblitz
2. node index.js
3. Open graphiql
4. Run the query
5. Look in console, it will say
```js
cache miss
cache miss
onExecuteDone {
  data: [Object: null prototype] {
    __responseCacheTypeName: 'Query',
    product: [Object: null prototype] {
      __responseCacheTypeName: 'Product',
      price: [Object: null prototype]
    }
  }
}
```

**Expected behavior**

Basically I expected
```js
cache miss
cache miss
onExecuteDone {
  data: [Object: null prototype] {
    product: [Object: null prototype] {
      price: [Object: null prototype]
    }
  }
}
```
So I don't get a lot of diffs like these in my jest snapshots:

```js
        "_entities": [
          {
            "withInput": {
              "price": {
    +           "__responseCacheTypeName": "PriceAmount",
                "amount": 557600,
                "display": "SEK 557,600",
              },
            },
            "withoutInput": {
              "price": {
    +           "__responseCacheTypeName": "PriceAmount",
                "amount": 557600,
                "display": "557 600 kr",
              },
            },
          },
```

**Environment:**

- OS: Mac
- NodeJS: 18.18
-    "@graphql-yoga/plugin-response-cache": "2.2.0",
-   "graphql-yoga": "4.0.5"

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
fixes #1968

### CODE REVIEW

**Comment by klippx** [comment]
@EmrysMyrddin You forgot to add a changeset. When can we get a (preview) release of this change?

**Comment by EmrysMyrddin** [comment]
Ah yes, this was merged a little soon >< I will try to add the changeset today.

You should be able to use the latest alpha, I have to check on GitHub actions the number generated

**Comment by EmrysMyrddin** [comment]
@klippx You can see preview versions here: https://github.com/n1ru4l/envelop/pull/2036

I'm just waiting for the CI and I will release the patch.

**Comment by EmrysMyrddin** [comment]
@klippx This fix is now available in `@envelop/response-cache@6.0.1` version :-)

**Pull request merged**
