### PR TITLE
docs: add meta tags to plugin hub

### PR DESCRIPTION
**Pull request by saihaj**
Adds meta tags to plugin hub.

### CODE REVIEW

**Review by dotansimha — APPROVED** [review]
😍

**Comment by dotansimha** [comment]
Maybe also in codegen website?

**Comment by saihaj** [comment]
> Maybe also in codegen website?

yep working on that gonna test out deploy preview here first : )

**Comment by saihaj** [comment]
so tags are there but it is a ordering thing. The one that comes first is what things are showing and that is not what we want.  (You need FB account to view this debugger) https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fenvelop-5ke08ooa0-theguild.vercel.app%2Fplugins%2Fuse-parser-cache 

image

**Comment by saihaj** [comment]
works fine on twitter. Wouldn't work on FB or Slack cause they prioritize `title` tag whereas twitter has their own custom tag and then the `og:title` tag  
image

**Pull request merged**
