### PR TITLE
Fixes issues with generic-auth plugin and missing `directiveNode` 

### LINKED ISSUE #614: `@envelop/generic-auth`: docs and implementation are different
**Describe the bug**

There seems to be several differences between docs and implementation.

1. @envelop/generic-auth has no exported member named 'resolveUser'.

in the docs:

```
import { useGenericAuth, resolveUser, ValidateUserFn } from '@envelop/generic-auth';
```

But `resolveUser` does not exist. So this should be ResolveUserFn.

2. resolveUser does not exist in the type of GenericAuthPluginOptions

in the docs:

```
    useGenericAuth({
      resolveUser,
      validateUser,
      mode: 'protect-all',
    }),
```

But resolveUser does not exist in the type of GenericAuthPluginOptions as I saw implementation.
Here, `resolveUserFn: ResolveUserFn<UserType, ContextType>;` and `validateUser?: ValidateUserFn<UserType, ContextType>;` are different in naming convention. I think it's better to use same naming rule in terms of consistency.

**Environment:**

- "@envelop/generic-auth": "^1.0.0"
- "@envelop/core": "^1.0.3"
- NodeJS:

### PR DESCRIPTION
**Pull request by taneba**
## Description

Fixes #614 

1. Fixed the conflicts between documentation and implementation.
- Renamed resolveUserFn to resolveUser (this would be a breaking change)
- Fixed Documentation

2. Fixed: directiveNode is not passed to validateUser onExecute.
- Pass directiveNode correctly to validateUser when run it on onExecute
- Added test code for role-aware authentication
- Fixed Documentation

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test code for role-aware authentication
- [x] Tested on my personal project https://github.com/taneba/fullstack-graphql-app/blob/main/backend/src/getEnveloped.ts

"@envelop/generic-auth": "^1.0.0"
"@envelop/core": "^1.0.3"

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Further comments

1 test failed but this is the same in main branch so I left it as it is.

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @taneba ! Thank you for this PR. Maybe we can adjust the documentation instead of the code? This way maybe we can avoid the breaking change?

**Comment by taneba** [comment]
Thanks for taking your time, @dotansimha !
Yeah, you think it's better to avoid breaking change rather than match naming at this moment? If so, I'll revert the code changes and adjust the documentation :)

**Comment by taneba** [comment]
@dotansimha 
Updated, and changed version to patch :)

**Comment by dotansimha** [comment]
Thank you!

**Pull request merged**
